# Formal Education, Experience, or Technical Specialization: Which Best Predicts Developer Salaries?

A comparative analysis of education, experience, and technical specialization using the Stack Overflow Developer Survey.

## Research Question

> **What is the relative importance of formal education, experience, and professional specialization in predicting developer salaries?**

## Objectives

In this notebook we:

- Understand the Stack Overflow 2025 Developer Survey.
- Review the survey schema.
- Select variables relevant to the research question.
- Define the study population.
- Perform univariate exploratory data analysis.

## Setup

In [1]:
import pandas as pd

In [2]:
# Opting out of output truncation for better data understanding

pd.options.display.max_columns = None
pd.options.display.max_rows = None
pd.options.display.max_colwidth = None
pd.options.display.max_seq_items = None

## Data Loading & Inspection

The raw dataset can be found in `data/raw/results.csv`. The remote dataset can be found [here](https://media.githubusercontent.com/media/StackExchange/Survey/refs/heads/main/packages/archive/2025/results.csv).

In [3]:
url = "../data/raw/results.csv"

df = pd.read_csv(url, low_memory=False)

# Using low_memory=False to get more information on columns with mixed types

df.head()

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,PlatformHaveEntry,PlatformWantEntry,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,WebframeHaveEntry,WebframeWantEntry,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,DevEnvHaveEntry,DevEnvWantEntry,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning new coding techniques or programming language","Online Courses or Certification (includes all media types);Other online resources (e.g. standard search, forum, online community)","Yes, I learned how to use AI-enabled tools for my personal curiosity and/or hobbies",AI CodeGen tools or AI-enabled apps,14.0,"Developer, mobile",20 to 99 employees,People manager,Remote,"Yes, I influenced the purchase of a substantial addition to the tech stack",Work,10.0,7.0,9.0,6.0,3.0,11.0,12.0,1.0,8.0,14.0,NaN,15.0,7.0,8.0,12.0,11.0,1.0,6.0,13.0,3.0,16.0,NaN,Fintech,3.0,1.0,4.0,9.0,5.0,10.0,12.0,11.0,2.0,6.0,7.0,13.0,14.0,15.0,8.0,NaN,I'm not sure,I have neither consider or transitioned into a new career or industry,7.0,3.0,Ukraine,EUR European Euro,52800.0,Yes,Bash/Shell (all shells);Dart;SQL,Dart,Dart,NaN,NaN,Yes,Cloud Firestore;PostgreSQL,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Cloudflare;Firebase;Google Cloud;Gradle,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Android Studio;Notepad++;Visual Studio;Visual Studio Code;Xcode,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;Android,Windows;MacOS;Android;iOS;iPadOS,Confluence;GitHub;GitLab;Jira;Markdown File,Markdown File,Markdown File,NaN,NaN,"Stack Overflow;Reddit;GitHub (public projects, not private repos);YouTube;LinkedIn;Medium",NaN,NaN,NaN,NaN,Yes,openAI GPT (chatbot models);openAI Image generating models;openAI Reasoning models,NaN,NaN,NaN,NaN,Yes,A few times per week,Between 5 and 10 years,I have never participated in Q&A on Stack Overflow,NaN,1.0,NaN,6.0,2.0,3.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools monthly or infrequently",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning about a codebase;Writing code;Search for answers,Project planning;Deployment and monitoring;Learning new concepts or technologies,Documenting code;Debugging or fixing code;Testing code;Committing and reviewing code;Predictive analytics;Generating content or synthetic data;Creating or maintaining documentation,NaN,NaN,"AI solutions that are almost right, but not quite",No,"Yes, I use AI agents at work monthly or infrequently",Not at all or minimally,Software engineering,NaN,AI agents have increased my productivity.;AI agents have reduced the time spent on specific development tasks.,AI agents have helped me automate repetitive tasks.;AI agents have improved the quality of my code.;AI agents have accelerated my learning about new technologies or codebases.;AI agents have helped me solve complex problems more effectively.;AI agents have improved collaboration within my team.,NaN,NaN,NaN,I am concerned about the accuracy of the information provided by AI agents.;It takes significant time and effort to learn how to use AI agents effectively.,Integrating AI agents with my existing tools and workflows can be difficult.;My company's IT and/or InfoSec teams have strict rules that do not allow me to use AI agent tools or platforms,The cost of using certain AI agent platforms is a barrier.;I have concerns about the security and privacy of data when using AI agents.,NaN,NaN,NaN,NaN,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning new coding techniques or programming language","Online Courses or Certification (includes all media types);Other online resources (e.g. standard search, forum, online community);Books / Physical media;Videos (not associated with specific online course or certification);Stack Overflow or Stack Exchange","Yes, I learned how to use AI-enabled tools for my personal curiosity and/or hobbies",AI CodeGen tools or AI-enabled apps,10.0,"Developer, back-end",500 to 999 employees,Individual contributor,"Hybrid (some in-person, leans heavy to flexibility)",No,Personal Project,13.0,1.0,2.0,9.0,4.0,3.0,12.0,5.0,7.0,14.0,NaN,14.0,1.0,13.0,10.0,9.0,3.0,4.0,2.0,5.0,15.0,NaN,Retail and Consumer Services,10.0,8.0,3.0,9.0,12.0,1.0,6.0,2.0,11.0,4.0,7.0,13.0,14.0,15.0,5.0,NaN,I'm not sure,I have transitioned into a new career and/or industry voluntarily,6.0,5.0,Netherlands,EUR European Euro,90000.0,Yes,Java,Java;Python;Swift,Java,NaN,NaN,Yes,Dynamodb;MongoDB,Dynamodb;MongoDB,Dynamodb;MongoDB,NaN,NaN,Yes,Amazon Web Services (AWS);Datadog;Docker;Homebrew;Kubernetes;Maven (build tool);Terraform,Amazon Web Services (AWS);Datadog;Docker;Homebrew;Kubernetes;Maven (build tool);Terraform,Amazon Web Services (AWS);Datadog;Docker;Homebrew;Kubernetes;Maven (build tool);Terraform,NaN,NaN,Yes,Spring Boot,Spring Boot,Spring Boot,NaN,NaN,Yes,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;iOS;iPadOS,MacOS,Confluence;GitHub;Jira,Confluence;GitHub;Jira,Confluence;GitHub;Jira,NaN,NaN,"Stack Overflow;Discord;Reddit;Dev.to;Hacker News;GitHub (public projects, not private repos);Slack (public channels, not work);YouTube;Twitch;LinkedIn;Substack;Medium","Stack Overflow;Discord;Reddit;Dev.to;Hacker News;GitHub (public projects, not private repos);Slack (public channels, not work);YouTube;Twitch;LinkedIn;Substack;Medium","Stack Overflow;Discord;Reddit;Dev.to;Hacker News;GitHub (public projects, not private repos);Slack (public channels, not work);YouTube;Twitch;LinkedIn;Substack;Medium",NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,Not sure/can't remember,Multiple times per day,Between 10 and 15 years,"Infrequently, less than once per year","Chat (people);Message Boards;Long-form articles;Videos;Coding challenges;Logic games/puzzles;Lists of recommendations (tools, frameworks, technologies, etc.);Direct messaging of users;Job board;Day-in-the-life profiles/interviews with experts",6.0,NaN,5.0,8.0,2.0,4.0,9.0,10.0,11.0,15.0,NaN,"Yes, somewhat",About half of the time,"Yes, I use AI tools weekly",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning new concepts or technologies,Learning about a codebase;Project planning;Committing and reviewing code;Deployment and monitoring,Writing code;Documenting code;Debugging or fixing code;Testing code;Predictive analytics;Search for answers;Generating content or synthetic data;Creating or maintaining documentation,NaN,NaN,"AI solutions that are almost right, but not quite;Debugging AI-generated code is more time-consuming",No,"No, and I don't plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,It takes significant time and effort to learn how to use AI agents effectively.;The cost of using certain AI agent platforms is a barrier.,NaN,I am concerned about the accuracy of the information provided by AI agents.;I have concerns about the security and privacy of data when using AI agents.,Integrating AI agents with my existing tools and workflows can be difficult.;My company's IT and/or InfoSec teams have strict rules that do not allow me to use AI agent tools or platforms,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to fully understand something;When I want to learn best practices;When I want to compare different solutions;When I have ethical or security concerns about code,All skills. AI is a flop.,104413.0,9.0
2,3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-employed",None of the above,10.0,"Yes, I am not new to coding but am learning new coding techniques or programming language",Online Courses or Certification (includes all media types);Videos (not associated with specific online course or certification);Technical documentation (is generated for/by the tool or system),"Yes, I learned how to use AI-enabled tools for my personal curiosity and/or hobbies",AI CodeGen tools or AI-enabled apps;Technical documentation (is generated for/by the tool or system);Videos (not associated with specific online course or certification),12.0,"Developer, front-end",NaN,NaN,NaN,No,Work,12.0,2.0,3.0,7.0,5.0,10.0,13.0,1.0,4.0,14.0,NaN,8.0,1.0,2.0,12.0,13.0,3.0,9.0,4.0,11.0,15.0,NaN,Software Development,9.0,6.0,7.0,11.0,8.0,12.0,1.0,5.0,2.0,4.0,3.0,13.0,14.0,15.0,10.0,NaN,No,I have transitioned into a new career and/or industry involuntarily,3.0,3.0,Ukraine,UAH Ukrainian hryvnia,2214000.0,Yes,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,NaN,NaN,Yes,MongoDB;MySQL;PostgreSQL,Firebase Realtime Database;MongoDB,MongoDB,NaN,NaN,Yes,Datadog;Firebase;npm;pnpm,Amazon Web Services (AWS);Firebase;npm;pnpm;Vite,Firebase;npm;pnpm,NaN,NaN,Yes,Next.js;Node.js;React,Next.js;Node.js;React,Next.js;Node.js;React,NaN,Solid.js,Yes,Visual Studio Code,Visual Studio Code;Windsurf,Visual Studio Code,NaN,NaN,Google Gemini,Google Gemini;Shadcn/ui,Google Gemini,NaN,NaN,MacOS;Android,MacOS,GitHub;GitLab;Jira,GitHub;GitLab;Jira,GitHub;GitLab;Jira,NaN,NaN,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,NaN,NaN,Yes,Gemini (Flash general purpose models);openAI GPT (chatbot models),Gemini (Flash general purpose models);Gemini (Pro Reasoning models);openAI GPT (chatbot models),Gemini (Flash general purpose models);openAI GPT (chatbot models),NaN,NaN,Not sure/can't remember,A few times per week,Between 5 and 10 years,"Infrequently, less than once per year","Chat (people);Videos;Lists of recommendations (tools, frameworks, technologies, etc.);Chat (bot/AI)",3.0,NaN,4.0,5.0,1.0,2.0,7.0,9.0,11.0,15.0,NaN,Neutral,About half of the time,"Yes, I use AI tools daily",Favorable,Somewhat trust,Neither good or bad at handling complex tasks,Documenting code;Debugging or fixing code;Testing code;Creating or maintaining documentation;Learning new concepts or technologies,NaN,Project planning;Committing and reviewing code;Deployment and monitoring;Predictive analytics;Search for answers,Learning about a codebase;Writing code;Generating content or synthetic data,NaN,"AI solutions that are almost right, but not quite;Debugging AI-generated code is more time-consuming",No,"Yes, I use AI agents at work weekly","Yes, somewhat",Software engineering,Multi-platform search enablement,AI agents have increased my productivity.;AI agents have helped me automate repetitive tasks.;AI agents have accelerated my learning about new technologies or codebases.;AI agents have reduced the time spent on specific development tasks.,AI agents have improved the quality of my code.;AI agents have helped me solve complex problems more effectively.,AI agents have improved collaboration within my team.,NaN,NaN,It takes significant time and effort to learn how to use AI agents effectively.;The cost of using certain AI agent platforms is a barrier.,My company's IT and/or InfoSec teams have strict rules that do not allow me to use AI agent tools or platforms,NaN,I am concerned about the accuracy of the information provided by AI agents.;Integrating AI agents with my existing tools and workflows can be difficult.;I have concerns about the security and privacy of data when using AI agents.,NaN,Redis,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to fully understand something;When I want to learn best practices;When I have ethical or security concerns about code;When I’m stuck and can’t explain the problem,"Understand how things actually work, problem solving, and algorithms",53061.0,8.0
3,4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning new coding techniques or programming language","Other online resources (e.g. standard search, forum, online community);Videos (not associated with specific online course or certification);Stack Overflow or Stack Exchange;Technical documentation (is generated for/by the tool or system);AI CodeGen tools or AI-enabled apps","Yes, I learned how to use AI-enabled tools for my personal curiosity and/or hobbies","AI CodeGen tools or AI-enabled apps;Videos (not associated with specific online course or certification);Other online resources (e.g. standard search, forum, online community)",5.0,"Developer, back-end","10,000 or more employees",Individual contributor,Remote,No,Personal Project,2.0,12.0,6.0,5.0,13.0,3.0,8.0,11.0,7.0,14.0,NaN,10.0,5.0,8.0,4.0,13.0,12.0,2.0,7.0,1.0,15.0,NaN,Retail and Consumer Services,1.0,2.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,3.0,NaN,No,I have neither consider or transitioned into a new career or industry,NaN,NaN,Ukraine,EUR European Euro,31200.0,Yes,Java;Kotlin;SQL,Java;Kotlin,Java;Kotlin,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Google Cloud,Amazon Web Services (AWS);Google Cloud,Amazon Web Services (AWS);Google Cloud,NaN,NaN,Yes,Spring Boot,Spring Boot,Spring Boot,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Amazon Bedrock,NaN,NaN,NaN,NaN,Windows,Windows;Ubuntu,GitLab;Jira;Miro,GitLab;Jira,GitLab;Jira,NaN,NaN,Stack Overflow;Reddit;YouTube;LinkedIn,"Stack Overflow;Reddit;GitHub (public projects, not private repos);YouTube;LinkedIn",Stack Overflow;Reddit;YouTube;LinkedIn,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,A few times per month or weekly,Between 3 and 5 years,I have never participated in Q&A on Stack Overflow,Videos;Chat (bot/AI),1.0,NaN,4.0,5.0,6.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools weekly",Favorable,Somewhat trust,Bad at handling complex tasks,NaN,Project planning;Documenting code;Testing code;Committing and reviewing code;Deployment and monitoring;Creating or maintaining documentation,Learning about a codebase;Writing code;Debugging or fixing code;Predictive analytics,Search for answers;Generating content or synthetic data;Learning new concepts or technologies,NaN,"AI solutions that are almost right, but not quite;I don’t use AI tools regularly",NO,"Yes, I use AI agents at work monthly or infrequently",Not at all or minimally,Software engineering,Language processing,AI agents have accelerated my learning about new technologies or codebases.,AI agents have increased my productivity.;AI agents have improved the quality of my code.;AI agents have helped me solve complex problems more effectively.;AI agents have reduced the time spent on specific development tasks.;AI agents have improved collaboration within my team.,AI agents have helped me automate repetitive tasks.,NaN,NaN,It takes significant time and effort to learn how to use AI agents effectively.;The cost of using certain AI agent platforms is a barrier.,NaN,I am concerned about the accuracy of the information provided by AI agents.;I have concerns about the security and privacy of data when using AI agents.;My company's IT and/or InfoSec teams have strict rules that do not allow me to use AI agent tools or platforms,Integrating AI agents with my existing tools and workflows can be difficult.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to fully understand something;When I have ethical or security concerns about code;When I’m stuck and can’t explain the problem,NaN,36197.0,6.0

In [4]:
# Data Summary

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 49191 entries, 0 to 49190
Columns: 172 entries, ResponseId to JobSat
dtypes: float64(52), int64(1), str(119)
memory usage: 64.6 MB

In [5]:
# Data Shape

df.shape # 49,191 rows, 172 columns

(49191, 172)

In [6]:
# Summary Statistics

df.describe()

,ResponseId,WorkExp,YearsCode,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,ToolCountWork,ToolCountPersonal,CompTotal,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,ConvertedCompYearly,JobSat
count,49191.000000,42893.000000,43042.000000,35975.000000,35975.000000,35975.000000,35975.000000,35975.000000,35975.000000,35975.000000,35975.000000,35975.000000,35975.000000,34259.000000,34259.000000,34259.000000,34259.000000,34259.000000,34259.000000,34259.000000,34259.000000,34259.000000,34259.000000,24943.000000,24943.000000,24943.000000,24943.000000,24943.000000,24943.000000,24943.000000,24943.000000,24943.000000,24943.000000,24943.000000,24943.000000,24943.000000,24943.000000,24943.000000,27611.000000,25582.000000,2.486600e+04,26260.000000,24340.000000,26260.000000,26260.000000,26260.000000,26260.000000,26260.000000,26260.000000,26260.000000,26260.000000,2.394700e+04,26670.000000
mean,24596.000000,13.367403,16.570861,7.867352,4.104211,4.110271,5.678193,4.119388,5.225990,6.477387,4.370841,4.431661,9.854315,8.307948,4.524067,5.925567,4.991710,4.048980,3.799323,4.365831,5.059867,5.508538,9.945766,6.867738,5.216173,7.455719,9.537947,9.758209,8.194965,5.884096,7.367799,6.744658,7.512569,5.703283,8.563324,8.679349,14.687487,7.826685,17.734852,8.545579,2.234198e+70,4.907845,3.339770,5.718355,4.561767,4.790861,5.199657,5.676314,4.984653,7.099505,10.079284,1.017615e+05,7.201950
std,14200.362883,10.800117,11.787610,2.397432,2.275821,2.329536,2.398084,2.437945,2.801045,2.331468,2.357058,2.620901,1.975692,2.202164,2.282867,2.301937,2.294707,2.607443,2.499468,2.557152,2.533541,2.906146,2.087463,3.741490,3.660632,3.726759,3.781286,3.557588,3.801257,3.900813,4.118532,3.888845,3.847265,4.110528,3.545288,3.633175,1.898188,4.077460,269.810134,44.664738,3.523096e+72,2.682204,2.411404,2.628016,3.070548,2.643177,2.563562,2.310659,2.490095,2.469394,1.940928,4.617569e+05,1.997245
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000e+00,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000e+00,0.000000
25%,12298.500000,5.000000,8.000000,7.000000,2.000000,2.000000,4.000000,2.000000,3.000000,5.000000,2.000000,2.000000,10.000000,8.000000,3.000000,4.000000,3.000000,2.000000,2.000000,2.000000,3.000000,3.000000,10.000000,4.000000,2.000000,4.000000,7.000000,7.000000,5.000000,2.000000,4.000000,3.000000,4.000000,2.000000,6.000000,6.000000,15.000000,4.000000,4.000000,3.000000,5.500000e+04,3.000000,1.000000,3.000000,1.000000,3.000000,3.000000,4.000000,3.000000,6.000000,10.000000,3.817100e+04,6.000000
50%,24596.000000,10.000000,14.000000,9.000000,4.000000,4.000000,6.000000,4.000000,5.000000,7.000000,4.000000,4.000000,10.000000,9.000000,4.000000,6.000000,5.000000,4.000000,3.000000,4.000000,5.000000,6.000000,10.000000,6.000000,4.000000,7.000000,10.000000,10.000000,8.000000,5.000000,7.000000,6.000000,7.000000,5.000000,9.000000,9.000000,15.000000,8.000000,6.000000,5.000000,1.050000e+05,5.000000,2.000000,6.000000,4.000000,5.000000,5.000000,6.000000,5.000000,8.000000,10.000000,7.532000e+04,8.000000
75%,36893.500000,20.000000,24.000000,9.000000,6.000000,6.000000,8.000000,6.000000,8.000000,8.000000,6.000000,7.000000,10.000000,9.000000,6.000000,8.000000,7.000000,6.000000,6.000000,6.000000,7.000000,8.000000,10.000000,10.000000,8.000000,11.000000,13.000000,13.000000,11.000000,9.000000,11.000000,10.000000,11.000000,9.000000,12.000000,12.000000,15.000000,11.000000,10.000000,7.000000,2.400000e+05,7.000000,5.000000,8.000000,7.000000,7.000000,7.000000,7.000000,7.000000,9.000000,10.000000,1.205960e+05,8.000000
max,49191.000000,100.000000,100.000000,14.000000,14.000000,14.000000,14.000000,14.000000,14.000000,14.000000,14.000000,14.000000,14.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,14.000000,15.000000,15.000000,16.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,10000.000000,1000.000000,5.555556e+74,15.000000,10.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,5.000000e+07,10.000000

In [7]:
# Null Assessment

df.isna().sum().sort_values(ascending=False)

AIAgentObsWrite                             48927
SOTagsWant Entry                            48761
SOTagsHaveEntry                             48733
AIModelsWantEntry                           48716
AIAgentOrchWrite                            48713
JobSatPoints_15_TEXT                        48527
AIAgentKnowWrite                            48425
AIModelsHaveEntry                           48415
SO_Actions_15_TEXT                          48368
AIAgentExtWrite                             48332
CommPlatformWantEntr                        48007
CommPlatformHaveEntr                        47715
DatabaseWantEntry                           47658
OfficeStackWantEntry                        47574
TechOppose_15_TEXT                          47544
TechEndorse_13_TEXT                         47182
DevEnvWantEntry                             47079
DatabaseHaveEntry                           47041
OfficeStackHaveEntry                        46602
WebframeWantEntry                           46561
AIAgentObserveSecure                        46499
DevEnvHaveEntry                             46429
PlatformWantEntry                           46091
LanguagesWantEntry                          46041
WebframeHaveEntry                           45897
AIAgentKnowledge                            45790
AIAgentOrchestration                        45431
AIAgentImpactStrongly disagree              45412
PlatformHaveEntry                           45234
LanguagesHaveEntry                          45209
AIAgentImpactSomewhat disagree              43400
AgentUsesGeneral                            43386
AIAgentImpactStrongly agree                 42504
AIAgentExternal                             40859
AIAgentChallengesStrongly disagree          39877
AIAgentImpactNeutral                        39516
AIAgentImpactSomewhat agree                 39045
AIToolCurrently mostly AI                   37966
AIModelsAdmired                             37907
AIModelsWantToWorkWith                      37346
AIAgentChallengesSomewhat disagree          37066
SOTagsAdmired                               36951
AIAgent_Uses                                36871
AIToolPlan to mostly use AI                 36373
SOTagsWantToWorkWith                        35604
WebframeAdmired                             33482
AIModelsHaveWorkedWith                      32910
DatabaseAdmired                             31896
WebframeWantToWorkWith                      31552
PlatformAdmired                             31369
SOTagsHaveWorkedWith                        31269
PlatformWantToWorkWith                      29776
DevEnvsAdmired                              29699
DatabaseWantToWorkWith                      29458
DevEnvsWantToWorkWith                       28577
AIToolCurrently partially AI                28163
AIAgentChallengesNeutral                    27896
AIAgentChallengesSomewhat agree             27244
OfficeStackAsyncAdmired                     26983
AIOpen                                      26651
AIToolPlan to partially use AI              26635
SO_Dev_Content                              26355
CommPlatformAdmired                         26314
WebframeHaveWorkedWith                      26199
AIAgentChallengesStrongly agree             26083
OfficeStackAsyncWantToWorkWith              25985
CommPlatformWantToWorkWith                  25840
LanguageAdmired                             25721
ConvertedCompYearly                         25244
PlatformHaveWorkedWith                      24933
SO_Actions_16                               24851
CompTotal                                   24325
JobSatPoints_5                              24248
JobSatPoints_1                              24248
JobSatPoints_3                              24248
JobSatPoints_4                              24248
JobSatPoints_2                              24248
JobSatPoints_6                              24248
JobSatPoints_13                             24248
JobSatPoints_16                             24248
JobSatPoints_15                             24248
JobSatPoints_14                             24248
JobSatPoints_7                              24248
JobSatPoints_10                             24248
JobSatPoints_11                             24248
JobSatPoints_8                              24248
JobSatPoints_9                              24248
AIToolDon't plan to use AI for this task    23810
DatabaseHaveWorkedWith                      23641
ToolCountPersonal                           23609
DevEnvsHaveWorkedWith                       23172
SO_Actions_15                               22931
SO_Actions_1                                22931
SO_Actions_3                                22931
SO_Actions_4                                22931
SO_Actions_7                                22931
SO_Actions_9                                22931
SO_Actions_6                                22931
SO_Actions_5                                22931
SO_Actions_10                               22931
AIExplain                                   22605
JobSat                                      22521
LanguageWantToWorkWith                      22112
ToolCountWork                               21580
AILearnHow                                  20934
OpSysProfessional use                       20308
AIHuman                                     19997
OfficeStackAsyncHaveWorkedWith              19333
CommPlatformHaveWorkedWith                  19126
AIModelsChoice                              18952
SOFriction                                  18404
DevEnvsChoice                               18112
WebframeChoice                              17998
PlatformChoice                              17929
OpSysPersonal use                           17774
AIFrustration                               17669
LanguageHaveWorkedWith                      17520
AIAgentChange                               17513
DatabaseChoice                              17503
SOComm                                      17485
AIAgents                                    17272
LanguageChoice                              16977
SOPartFreq                                  16963
SODuration                                  16564
SOVisitFreq                                 16481
SOAccount                                   16394
ICorPM                                      15948
AIComplex                                   15908
AIAcc                                       15894
AISent                                      15724
LearnCode                                   15635
Industry                                    15549
AISelect                                    15471
RemoteWork                                  15411
OrgSize                                     15013
TechOppose_9                                14932
TechOppose_15                               14932
TechOppose_2                                14932
TechOppose_1                                14932
TechOppose_16                               14932
TechOppose_13                               14932
TechOppose_11                               14932
TechOppose_3                                14932
TechOppose_5                                14932
TechOppose_7                                14932
Currency                                    13754
Country                                     13754
NewRole                                     13664
TechEndorse_3                               13216
TechEndorse_1                               13216
TechEndorse_2                               13216
TechEndorse_4                               13216
TechEndorse_5                               13216
TechEndorse_7                               13216
TechEndorse_8                               13216
TechEndorse_9                               13216
TechEndorse_6                               13216
TechEndorse_13                              13216
AIThreat                                    13113
PurchaseInfluence                           11754
TechEndorseIntro                            11635
WorkExp                                      6298
YearsCode                                    6149
DevType                                      5511
EmploymentAddl                               4316
LearnCodeAI                                  3990
LearnCodeChoose                              2333
EdLevel                                      1042
Employment                                    852
MainBranch                                      0
Age                                             0
ResponseId                                      0
dtype: int64

In [8]:
df["MainBranch"].value_counts() # Exclusion/Inclusion Criteria

MainBranch
I am a developer by profession                                                                37467
I am not primarily a developer, but I write code sometimes as part of my work/studies          4894
I am learning to code                                                                          2585
I code primarily as a hobby                                                                    1924
I used to be a developer by profession, but no longer am                                       1325
I work with developers or my work supports developers but am not a developer by profession      996
Name: count, dtype: int64

## Schema Exploration

The schema for this dataset can be found in `schema/schema.csv`.

In [9]:
# Reviewing the survey schema and column definitions

schema_url = "../schema/schema.csv"

schema = pd.read_csv(schema_url)

schema[["qname", "question"]]

,qname,question
0,TechEndorse_1,What attracts you to a technology or causes you to endorse it (most to least important)?
1,TechEndorse_2,What attracts you to a technology or causes you to endorse it (most to least important)?
2,TechEndorse_3,What attracts you to a technology or causes you to endorse it (most to least important)?
3,TechEndorse_4,What attracts you to a technology or causes you to endorse it (most to least important)?
4,TechEndorse_5,What attracts you to a technology or causes you to endorse it (most to least important)?
5,TechEndorse_6,What attracts you to a technology or causes you to endorse it (most to least important)?
6,TechEndorse_7,What attracts you to a technology or causes you to endorse it (most to least important)?
7,TechEndorse_8,What attracts you to a technology or causes you to endorse it (most to least important)?
8,TechEndorse_9,What attracts you to a technology or causes you to endorse it (most to least important)?
9,TechEndorse_13,What attracts you to a technology or causes you to endorse it (most to least important)?
10,TechEndorse_13_TEXT,What attracts you to a technology or causes you to endorse it (most to least important)?
11,TechOppose_1,What would turn you off or cause you to reject it (most to least important)?
12,TechOppose_2,What would turn you off or cause you to reject it (most to least important)?
13,TechOppose_3,What would turn you off or cause you to reject it (most to least important)?
14,TechOppose_5,What would turn you off or cause you to reject it (most to least important)?
15,TechOppose_7,What would turn you off or cause you to reject it (most to least important)?
16,TechOppose_9,What would turn you off or cause you to reject it (most to least important)?
17,TechOppose_11,What would turn you off or cause you to reject it (most to least important)?
18,TechOppose_13,What would turn you off or cause you to reject it (most to least important)?
19,TechOppose_16,What would turn you off or cause you to reject it (most to least important)?
20,TechOppose_15,What would turn you off or cause you to reject it (most to least important)?
21,TechOppose_15_TEXT,What would turn you off or cause you to reject it (most to least important)?
22,JobSatPoints_1,"Rank the following attributes of your current professional job in technology according to those that contribute your job satisfaction so that the first is the most important, last is least important (if you just started a new job, consider the job you spent the most time at in the past year):"
23,JobSatPoints_2,"Rank the following attributes of your current professional job in technology according to those that contribute your job satisfaction so that the first is the most important, last is least important (if you just started a new job, consider the job you spent the most time at in the past year):"
24,JobSatPoints_16,"Rank the following attributes of your current professional job in technology according to those that contribute your job satisfaction so that the first is the most important, last is least important (if you just started a new job, consider the job you spent the most time at in the past year):"
25,JobSatPoints_3,"Rank the following attributes of your current professional job in technology according to those that contribute your job satisfaction so that the first is the most important, last is least important (if you just started a new job, consider the job you spent the most time at in the past year):"
26,JobSatPoints_4,"Rank the following attributes of your current professional job in technology according to those that contribute your job satisfaction so that the first is the most important, last is least important (if you just started a new job, consider the job you spent the most time at in the past year):"
27,JobSatPoints_5,"Rank the following attributes of your current professional job in technology according to those that contribute your job satisfaction so that the first is the most important, last is least important (if you just started a new job, consider the job you spent the most time at in the past year):"
28,JobSatPoints_6,"Rank the following attributes of your current professional job in technology according to those that contribute your job satisfaction so that the first is the most important, last is least important (if you just started a new job, consider the job you spent the most time at in the past year):"
29,JobSatPoints_7,"Rank the following attributes of your current professional job in technology according to those that contribute your job satisfaction so that the first is the most important, last is least important (if you just started a new job, consider the job you spent the most time at in the past year):"
30,JobSatPoints_8,"Rank the following attributes of your current professional job in technology according to those that contribute your job satisfaction so that the first is the most important, last is least important (if you just started a new job, consider the job you spent the most time at in the past year):"
31,JobSatPoints_9,"Rank the following attributes of your current professional job in technology according to those that contribute your job satisfaction so that the first is the most important, last is least important (if you just started a new job, consider the job you spent the most time at in the past year):"
32,JobSatPoints_10,"Rank the following attributes of your current professional job in technology according to those that contribute your job satisfaction so that the first is the most important, last is least important (if you just started a new job, consider the job you spent the most time at in the past year):"
33,JobSatPoints_11,"Rank the following attributes of your current professional job in technology according to those that contribute your job satisfaction so that the first is the most important, last is least important (if you just started a new job, consider the job you spent the most time at in the past year):"
34,JobSatPoints_13,"Rank the following attributes of your current professional job in technology according to those that contribute your job satisfaction so that the first is the most important, last is least important (if you just started a new job, consider the job you spent the most time at in the past year):"
35,JobSatPoints_14,"Rank the following attributes of your current professional job in technology according to those that contribute your job satisfaction so that the first is the most important, last is least important (if you just started a new job, consider the job you spent the most time at in the past year):"
36,JobSatPoints_15,"Rank the following attributes of your current professional job in technology according to those that contribute your job satisfaction so that the first is the most important, last is least important (if you just started a new job, consider the job you spent the most time at in the past year):"
37,JobSatPoints_15_TEXT,"Rank the following attributes of your current professional job in technology according to those that contribute your job satisfaction so that the first is the most important, last is least important (if you just started a new job, consider the job you spent the most time at in the past year):"
38,SO_Actions_1,"When visiting Stack Overflow, which following activities are you most interested in? Please rank the following so the first activity is what most interests you and last is your least interested activity."
39,SO_Actions_16,"When visiting Stack Overflow, which following activities are you most interested in? Please rank the following so the first activity is what most interests you and last is your least interested activity."
40,SO_Actions_3,"When visiting Stack Overflow, which following activities are you most interested in? Please rank the following so the first activity is what most interests you and last is your least interested activity."
41,SO_Actions_4,"When visiting Stack Overflow, which following activities are you most interested in? Please rank the following so the first activity is what most interests you and last is your least interested activity."
42,SO_Actions_5,"When visiting Stack Overflow, which following activities are you most interested in? Please rank the following so the first activity is what most interests you and last is your least interested activity."
43,SO_Actions_6,"When visiting Stack Overflow, which following activities are you most interested in? Please rank the following so the first activity is what most interests you and last is your least interested activity."
44,SO_Actions_9,"When visiting Stack Overflow, which following activities are you most interested in? Please rank the following so the first activity is what most interests you and last is your least interested activity."
45,SO_Actions_7,"When visiting Stack Overflow, which following activities are you most interested in? Please rank the following so the first activity is what most interests you and last is your least interested activity."
46,SO_Actions_10,"When visiting Stack Overflow, which following activities are you most interested in? Please rank the following so the first activity is what most interests you and last is your least interested activity."
47,SO_Actions_15,"When visiting Stack Overflow, which following activities are you most interested in? Please rank the following so the first activity is what most interests you and last is your least interested activity."
48,SO_Actions_15_TEXT,"When visiting Stack Overflow, which following activities are you most interested in? Please rank the following so the first activity is what most interests you and last is your least interested activity."
49,MainBranch,Are you someone who writes code? Please select one of the following options that best describes you today.
50,Age,What is your age?
51,EdLevel,Which of the following best describes the highest level of formal education that you’ve completed?
52,Employment,Which of the following best describes your current employment status?<br>
53,EmploymentAddl,Which of the following <strong>additional</strong> activities are you currently engaged in?
54,WorkExp,"How many years of professional work experience do you have? Please round to the nearest whole number, excluding any decimal points. If your answer is '0', please leave blank."
55,LearnCodeChoose,Did you begin learning to code or learn a new coding skill/programming language in the last year?
56,LearnCode,How did you learn to code in the past year? Select all that apply.
57,LearnCodeAI,Did you spend time in the last year learning AI programming or AI-enabled tooling on your own or at work?
58,AILearnHow,How did you learn to code for AI in the past year? Select all that apply.
59,YearsCode,"Including any education, how many years have you been coding in total? Please round to the nearest whole number, excluding any decimal points."
60,DevType,Which of the following describes your current job or the job you had for the most time in the past year?
61,OrgSize,"Approximately how many people are employed by your employer? This should only include your primary company, and if there was more than one employer please consider the one you spent most of your time working for in the past year."
62,ICorPM,Are you an individual contributor or people manager?
63,RemoteWork,Which best describes your current work situation?
64,PurchaseInfluence,Have you <strong>influenced or endorsed</strong> a new technology purchase at your organization or sole proprietor job in the past year?
65,TechEndorseIntro,"When you&rsquo;re in a position to <strong>influence or endorse a technology</strong>, whether at work, for school, or for a personal project you&rsquo;re responsible for, what features or attributes matter most when deciding to support a tool? What factors would be deal-breakers?<br />\n<br />\nFirst, select the context (work, school, personal project). Then, rank the following features in order of importance.​​​​​​"
66,Industry,What industry do you work for in?
67,JobSat,How satisfied are you in your current professional developer role?
68,AIThreat,Do you believe AI is a threat to your current job?
69,NewRole,Have you considered a career change or transitioned into a new role in the past year?
70,ToolCountWork,"For your <b>primary work role</b> (student, developer, or technologist) over the past year:\n<br><br>Excluding general operating systems (like Windows or macOS) and web browsers, <b>how many distinct software applications or platforms</b> did you regularly use to create, analyze, manage, or share information in order to do your job?\n\nPlease enter a whole number below with no punctuation, or leave blank."
71,ToolCountPersonal,"<b></b>For your <b>side projects or other personal work</b> over the past year (focus on the project you spent the most time on if applicable):\n<br><br>Excluding general operating systems and web browsers, how many <b>distinct software applications or platforms</b> did you regularly use to do your job? Please enter a whole number below with no punctuation, or leave blank."
72,Country,Where do you live?
73,Currency,"Which currency do you use day-to-day? If your answer is complicated, please pick the one you're most comfortable estimating in."
74,CompTotal,"What is your current total <b>annual</b> compensation (salary, bonuses, and perks, before taxes and deductions) in terms of your day-to-day currency? Please enter a whole number in the box below, without any punctuation. If you are paid hourly, please estimate an equivalent yearly salary. If you prefer not to answer, please leave the box empty."
75,LanguageChoice,"Did you work with programming, scripting and markup languages in the last year or do you plan to in the year to come? Here, we are referring to anything you use that is conventionally referred to as code."
76,Language,"Which <b>programming, scripting, and markup languages</b> have you done extensive development work in over the past year, and which do you want to work in over the next year? (If you both worked with the language and want to continue to do so, please check both boxes in that row.)"
77,LanguagesHaveEntry,"Was the programming language you use not listed above? List below, separated by a comma and a space for each, the programming language(s) <strong>you used in the past year</strong>."
78,LanguagesWantEntry,"Was the programming language you want to use not listed above? List below, separated by a comma and a space for each, the programming language(s) <strong>you want to use next year</strong>."
79,DatabaseChoice,"Did you work with database environments in the last year or do you plan to in the year to come? Here, we are referring to a system of managing structured data, mostly outside of your local machine."
80,Database,"Which <b>database environments </b>have you done extensive development work in over the past year, and which do you want to work in over the next year? (If you both worked with the database and want to continue to do so, please check both boxes in that row.)"
81,DatabaseHaveEntry,"Was the database environment you use not listed above? List below, separated by a comma and a space for each, what <strong>you used in the past year</strong>."
82,DatabaseWantEntry,"Was the database environment you want to use not listed above? List below, separated by a comma and a space for each, what <strong>you want to use next year</strong>."
83,PlatformChoice,"Did you work with cloud platforms, containerization/orchestration tools, package managers, build tools or infrastructure as code solutions in the last year or do you plan to in the year to come? Here, we are referring to tooling that automates, manages, and scales the entire application lifecycle, often leveraging remote, virtualized resources."
84,Platform,"Which <b>cloud platforms, containerization/orchestration tools, package managers, build tools, and infrastructure as code solutions</b> have you done extensive development work in over the past year, and which do you want to work in over the next year? (If you both worked with the platform and want to continue to do so, please check both boxes in that row.)"
85,PlatformHaveEntry,"Was the cloud platforms, containerization/orchestration tools, package managers, build tools, and infrastructure as code solutions you use not listed above? List below, separated by a comma and a space for each, what <strong>you used in the past year</strong>."
86,PlatformWantEntry,"Was the cloud platforms, containerization/orchestration tools, package managers, build tools, and infrastructure as code solutions you want to use not listed above? List below, separated by a comma and a space for each, what<strong>you want to use next year</strong>."
87,WebframeChoice,"Did you work with web frameworks and web technologies in the last year or do you plan to in the year to come? Here, we are referring to technology that helps website and web apps materialize."
88,Webframe,"Which <b>web frameworks and web technologies</b> have you done extensive development work in over the past year, and which do you want to work in over the next year? (If you both worked with the framework and want to continue to do so, please check both boxes in that row.)"
89,WebframeHaveEntry,"Were the web frameworks and web technologies you use not listed above? List below, separated by a comma and a space for each, what <strong>you used in the past year</strong>."
90,WebframeWantEntry,"Were the web frameworks and web technologies you want to use not listed above? List below, separated by a comma and a space for each, the what <strong>you want to use next year</strong>."
91,DevEnvsChoice,"Did you work with development environments or AI-enabled code editing tools in the last year or do you plan to in the year to come? Here, we are referring to programs like VS Code that allow you to write, edit and save code easily and help you share code with other developers or AI agents."
92,DevEnvs,"Which <strong>development environments and AI-enabled code editing tools</strong> did you use regularly over the past year, and which do you want to work with over the next year? Please check all that apply."
93,DevEnvHaveEntry,"Was the developer environment or AI-enabled code editing tool you use not listed above? List below, separated by a comma and a space for each, what<strong> you used in the past year</strong>."
94,DevEnvWantEntry,"Was the developer environment or AI-enabled code editing tool you want to use not listed above? List below, separated by a comma and a space for each, what <strong>you want to use next year</strong>."
95,SOTags,"Which rising technology of the added as <b>new tag or tag subject area on Stack Overflow</b> in the last three years <strong>have you used</strong> regularly in the past year, and which do you <strong>want to work with</strong> over the next year? Please check all that apply.<br>\n"
96,SOTagsHaveEntry,"Was the new tag on Stack Overflow (i.e. added in the last 2 - 3 years) you use not listed above? List below, separated by a comma and a space for each, what <strong>you used in the past year</strong>."
97,SOTagsWant Entry,"Was the new tag on Stack Overflow (i.e. added in the last 2 - 3 years) you want to use not listed above? List below, separated by a comma and a space for each, what <strong>you want to use next year</strong>."
98,OpSys,What is the primary <b>operating system</b> in which you work?
99,OfficeStackAsync,"Which <b>collaborative work management and/or code documentation tools</b> did you use regularly over the past year, and which do you want to work with over the next year? Select all that apply"
100,OfficeStackHaveEntry,"Was the collaborative work management and/or code documentation tools you use not listed above? List below, separated by a comma and a space for each, what you used in the past year."

### Key Takeaways

- The dataset contains 172 variables.
- Variables span demographics, education, employment, technology use, compensation, and developer preferences.
- A schema file is available and will be used to guide feature selection.
- Subsequent work will focus on preparing the dataset for analysis.